// Copyright (c) 2024-present The Navio Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_UTIL_SOCK_WS_H
#define BITCOIN_UTIL_SOCK_WS_H

#include <span.h>
#include <util/sock.h>

#include <cstddef>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

/**
 * A `Sock` that speaks a small RFC 6455 (WebSocket) server-side subset over an
 * accepted TCP socket, so that browser clients (which have no raw TCP) can take
 * part in the P2P network as ordinary peers.
 *
 * The WebSocket connection simply carries the normal P2P byte stream: binary
 * frames are chunks of that stream and frame boundaries carry no meaning.
 * `Recv()` performs the HTTP upgrade handshake, then decodes frames and hands
 * back only the unframed application payload. `Send()` wraps the given bytes
 * into unmasked binary frames.
 *
 * Supported: the HTTP/1.1 upgrade handshake, binary and continuation frames
 * (payloads are just appended), ping (answered with pong), pong (ignored) and
 * close (answered with close, then reported as EOF). Client frames must be
 * masked. Rejected as protocol errors: text frames, unmasked client frames,
 * RSV bits (no extensions are ever negotiated), unknown opcodes, fragmented or
 * oversized control frames and any frame payload larger than
 * `MAX_FRAME_PAYLOAD`. No TLS: front the listener with a reverse proxy for
 * `wss://`.
 *
 * Non-blocking contract (matches what `CConnman` expects from a plain `Sock`):
 * - `Recv()` returns the number of application bytes copied, `0` on EOF/close,
 *   or `-1` with `WSAEWOULDBLOCK` when no application bytes are available yet
 *   and `-1` with another error code on a protocol error.
 * - `Recv()` never buffers more decoded application bytes than the caller
 *   asked for: at most `len` raw bytes are read from the wire per call and the
 *   decoded payload can never exceed that. This is what makes it safe to wait
 *   for readability of the underlying file descriptor with `Wait()`/`WaitMany()`.
 * - `Send()` frames at most `MAX_SEND_FRAME` bytes per frame. The frame header
 *   is written first; if the underlying socket then accepts only part of the
 *   payload, the wrapper remembers how many payload bytes are still owed on
 *   that frame and writes exactly those many bytes raw (without a new header)
 *   on the following `Send()` calls. This relies on the caller re-offering the
 *   unsent tail of the same byte stream, which is how `CConnman::SocketSendData`
 *   behaves. Only tiny protocol-generated bytes (handshake reply, frame headers,
 *   pong/close frames) are ever buffered internally; they are flushed before
 *   anything else on the next `Send()`/`Recv()`.
 *
 * Both `Send()` and `Recv()` must be called with external synchronisation
 * (`CConnman` holds `CNode::m_sock_mutex` around both).
 */
class WebSocketSock : public Sock
{
public:
    /** Upper bound on the size of the HTTP upgrade request. */
    static constexpr size_t MAX_HANDSHAKE_BYTES{8 * 1024};
    /** Largest accepted payload of a single incoming frame. */
    static constexpr size_t MAX_FRAME_PAYLOAD{4 * 1024 * 1024};
    /** Largest payload of a single outgoing frame. */
    static constexpr size_t MAX_SEND_FRAME{64 * 1024};

    /**
     * Take over the file descriptor of an accepted TCP socket. `inner` is left
     * empty (`INVALID_SOCKET`) afterwards.
     */
    explicit WebSocketSock(std::unique_ptr<Sock>&& inner);

    ~WebSocketSock() override = default;

    WebSocketSock& operator=(Sock&& other) override;

    [[nodiscard]] ssize_t Send(const void* data, size_t len, int flags) const override;
    [[nodiscard]] ssize_t Recv(void* buf, size_t len, int flags) const override;

    /** Whether the HTTP upgrade handshake has been completed successfully. */
    [[nodiscard]] bool HandshakeComplete() const { return m_recv_state != RecvState::HANDSHAKE && m_hs_ok; }

    /**
     * Compute the `Sec-WebSocket-Accept` value for a `Sec-WebSocket-Key`
     * (RFC 6455 section 4.2.2). Exposed for tests.
     */
    static std::string ComputeAccept(const std::string& key);

protected:
    /** Construct from a raw file descriptor; used by test mocks. */
    explicit WebSocketSock(SOCKET s);

    /** Raw I/O on the underlying transport. Overridden by test mocks. */
    virtual ssize_t RawSend(const void* data, size_t len, int flags) const { return Sock::Send(data, len, flags); }
    virtual ssize_t RawRecv(void* buf, size_t len, int flags) const { return Sock::Recv(buf, len, flags); }

private:
    enum class RecvState {
        HANDSHAKE,       //!< Reading the HTTP upgrade request.
        FRAME_HEADER,    //!< Reading a frame header.
        DATA_PAYLOAD,    //!< Streaming a binary/continuation payload to the caller.
        CONTROL_PAYLOAD, //!< Collecting a (small) control frame payload.
        CLOSED,          //!< Peer sent a close frame; report EOF.
        FAILED,          //!< Protocol error; report an error.
    };

    /** Feed raw bytes from the wire through the handshake and frame decoders. */
    [[nodiscard]] bool Consume(const uint8_t* data, size_t len) const;
    /** Parse and answer a complete HTTP upgrade request. */
    [[nodiscard]] bool ProcessHandshake(std::string_view request) const;
    /** Parse a complete frame header held in `m_hdr_buf`. */
    [[nodiscard]] bool ProcessFrameHeader() const;
    /** Handle a complete control frame whose (masked) payload is in `m_hdr_buf`. */
    [[nodiscard]] bool ProcessControlFrame() const;

    /** Queue protocol-generated bytes (handshake reply, frame header) for sending. */
    void QueueRaw(Span<const uint8_t> bytes) const;
    /** Queue a control frame; deferred while a data frame is in flight. */
    void QueueControlFrame(uint8_t opcode, Span<const uint8_t> payload) const;
    /**
     * Try to write all internally buffered bytes.
     * @return true if nothing is left to flush, false otherwise (with the last
     * error set to `WSAEWOULDBLOCK` if the socket simply was not ready).
     */
    [[nodiscard]] bool FlushPending(int flags) const;
    /** Copy already-decoded application bytes to the caller. */
    ssize_t DrainAppBytes(void* buf, size_t len) const;

    // Receive side.
    mutable RecvState m_recv_state{RecvState::HANDSHAKE};
    mutable bool m_hs_ok{false};
    mutable std::vector<uint8_t> m_hs_buf;
    mutable std::vector<uint8_t> m_hdr_buf;
    mutable uint8_t m_opcode{0};
    mutable uint8_t m_mask[4]{};
    mutable size_t m_mask_idx{0};
    mutable uint64_t m_payload_remaining{0};
    mutable std::vector<uint8_t> m_app_out;
    mutable size_t m_app_out_pos{0};
    mutable std::vector<uint8_t> m_raw_buf;

    // Send side.
    mutable std::vector<uint8_t> m_send_pending;
    mutable size_t m_send_pending_pos{0};
    mutable std::vector<uint8_t> m_control_out;
    mutable size_t m_frame_remaining{0};
};

#endif // BITCOIN_UTIL_SOCK_WS_H
